travelblog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('website.urls',namespace='website')),
]

website/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^travels/$', views.travel_list, name='travels'),
    url(r'^travel/(?P<pk>[0-9]+)/$', views.travel_detail, name='travel_detail'),
]

website/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from future.utils import native
from future.builtins import str
from django.core.files.images import ImageFile

import os, sys, io

# Django properties
from django.core.files.storage import FileSystemStorage, get_storage_class, default_storage
from django.core.files.base import ContentFile
from django.core.files import File
from django.conf import settings
from django.db import models

# Fields
from django_countries.fields import CountryField
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from zipfile import ZipFile
from django.db.models.signals import post_delete


fs = FileSystemStorage(location=settings.STATIC_ROOT)

UPLOADS_GALLERY_DIRECTORY = 'travels'

class Gallery(models.Model):
    zipfile = models.FileField(verbose_name="Zip File", upload_to=UPLOADS_GALLERY_DIRECTORY,
        help_text="Upload a zip file containing images, and they'll be imported into this gallery.")

    class Meta:
        verbose_name = "Gallery"
        verbose_name_plural = "Galleries"


    def save(self, *args, **kwargs):
        super(Gallery, self).save(*args, **kwargs)
        if self.zipfile:
            from zipfile import ZipFile
            zip_file = ZipFile(self.zipfile)
            for name in zip_file.namelist():
                data = zip_file.read(name)
                try:
                    from PIL import Image
                    image = Image.open(io.BytesIO(data))
                    image.load()
                    image = Image.open(io.BytesIO(data))
                    image.verify()
                except ImportError:
                    pass
                except:
                    continue
                path = os.path.join(settings.MEDIA_ROOT, UPLOADS_GALLERY_DIRECTORY, native(str(name, errors="ignore")))
                img_tmp_path = default_storage.save(path, ContentFile(data))

                photo = Photo()
                photo.image.save(os.path.basename(img_tmp_path), File(open(img_tmp_path)))
                photo.album = os.path.splitext(os.path.split(zip_file.filename)[1])[0]
                photo.save()

                os.remove(img_tmp_path)
            zip_file.close()
            self.zipfile.delete(save=True)

class Photo(models.Model):
    image = models.ImageField(upload_to=UPLOADS_GALLERY_DIRECTORY)
    album = models.CharField(max_length=200)
    description = models.CharField(max_length=200, blank=True, null=True)
    banner = models.BooleanField(default=False)

    def __str__(self):
        return ("{}, {}").format(self.album, self.description)


class Travel(models.Model):
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    text = RichTextField()
    date =  models.DateTimeField()
    country = CountryField(blank_label='(select country)')
    city = models.CharField(max_length=100)
    address = models.CharField(max_length=100)
    geo = models.CharField(verbose_name=("Google Map"), max_length=500, blank=True, null=True,
        help_text="Insertar el enlace del mapa embebido de Google MyMaps.")
    price = models.IntegerField()
    score = models.IntegerField()
    season = models.CharField(max_length=50, default='verano', choices=(('invierno','Invierno'),('verano','Verano'),('primavera','Primavera'),('otoño','Otoño')))
    gallery = models.ManyToManyField(Photo)


    def __str__(self):
        return self.title

website/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from models import Travel
from django.core.files.storage import get_storage_class
from django.conf import settings

def home(request):
    travels = Travel.objects.all().order_by('-score')
    return render(request, 'index.html', {'travels':travels})

def travel_list(request):
    travels = Travel.objects.all().order_by('country')
    return render(request, 'travel/index.html', {'travels':travels})

def travel_detail(request, pk):
    travel = Travel.objects.get(pk=pk)

    travel.images = list()
    static_storage = get_storage_class(settings.STATICFILES_STORAGE)()
    img_dir = 'img/travel/{date}_{title}/'.format(date=travel.date.strftime('%Y_%m_%d'), title=travel.title)
    if static_storage.exists(img_dir):
        travel.images.extend([img_dir + x for x in static_storage.listdir(img_dir)[1]])
    return render(request, 'travel/detail.html', {'travel':travel})

def contact(request):
    return render(request, 'contact.html')

website/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="es">

<head>
  <title>ChooseTravel: {% block meta-title %}{% endblock %} </title>
  <meta name="description" content="{% block meta-description %}{% endblock %} ">

  <meta name="author" content="David Amrani Hernandez" />
  <meta name="keywords" content="travel, viajes, deporte, vuelo, precio, pais, ciudad" />
  <meta property="og:image" content="{% block meta-image %}{% endblock %}">
  <meta property="og:url" content="{% block meta-url %}{% endblock %}">


  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="robots" content="follow" />

  <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />

  <!-- Bootstrap JS <--></-->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/tether.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-select.js' %}"></script>
  <script src="{% static 'js/bootstrap-table.js' %}"></script>
  <script src="{% static 'js/bootstrap-table-export.js' %}"></script>
  <script src="{% static 'js/tableExport.js' %}"></script>

  <!-- Local CSS -->
  <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}"> -->
  <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}"> -->
  <link rel="stylesheet" href="{% static 'css/bootstrap-table.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}" />
  <link rel="stylesheet" href="{% static 'css/local-styles.css' %}">

</head>

<body>

  <div class="bg-inverse">
    <div class="container">
      <nav class="navbar navbar-toggleable-md sticky-top navbar-inverse mb-4">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'website:home' %}"><i class="fa fa-map-marker fa-lg text-warning"></i> Choose<span class="text-warning">Travel</span> </a>

        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item  {% if '/' == request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'website:home' %}"> Home</a>
            </li>
            <li class="nav-item  {% if '/travels/' == request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'website:travels' %}"> Viajes</a>
            </li>
            <li class="nav-item  {% if '/contact/' == request.path %}active{% endif %}">
              <a class="nav-link" href="{% url 'website:contact' %}"> Contacto</a>
            </li>
          </ul>
        </div>

        <div class="col-2 hidden-md-down">
          <a class="navbar-brand float-right" target="_blank" href="https://github.com/davidmoremad/"><i class="fa fa-github"></i></a>
          <a class="navbar-brand float-right" target="_blank" href="https://www.linkedin.com/in/davidah/"><i class="fa fa-linkedin"></i></a>
          <a class="navbar-brand float-right" target="_blank" href="https://www.instagram.com/davidmoremad"><i class="fa fa-instagram"></i></a>
          <a class="navbar-brand float-right" target="_blank" href="https://www.twitter.com/davidmoremad/"><i class="fa fa-twitter"></i></a>
        </div>

      </nav>
    </div>
  </div>

  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

  <div class="hidden-sm-up" style="height:450px"><br></div>
  <footer class="footer" id="footer">
    <div class="container">
        <!-- DESKTOP -->
        <div class="row hidden-md-down">
          <div class="col-md-6">
            <h5 class="text-white mt-4 mb-4"> <i class="fa fa-instagram text-warning"></i> Last on <a href="https://www.instagram.com/davidmoremad" target="_blank" class="text-warning">Instagram</a>!</h5>
            <iframe class="snapwidget-widget hidden-md-down" src="https://snapwidget.com/embed/485558" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:500px; height:125px"></iframe>
          </div>
          <div class="col-md-6">
            <h5 class="text-white mt-4 mb-4"> <i class="fa fa-facebook text-primary"></i> Last on <a href="https://www.facebook.com/davidmoremad" target="_blank" class="text-primary">Facebook</a>!</h5>
            <iframe class="snapwidget-widget hidden-md-down" src="https://snapwidget.com/embed/485561" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:500px; height:125px"></iframe>
          </div>
        </div>

        <!-- MOBILE -->
        <div class="hidden-sm-up">
            <h4 class="d-flex justify-content-between text-white mt-4 mb-4"> <i class="fa fa-instagram text-warning bg-inverse rounded p-2"></i> <span>Last on <a href="instagram://user?username=davidmoremad" target="_blank" class="text-warning">Instagram</a>!</span></h4>
            <iframe class="snapwidget-widget" src="https://snapwidget.com/embed/485558" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:350px; height:125px"></iframe>
            <h4 class="d-flex justify-content-between text-white mt-4 mb-4"> <i class="fa fa-facebook text-primary bg-inverse rounded p-2"></i> <span>Last on <a href="fb://profile/100021733520692" target="_blank" class="text-primary">Facebook</a>!</span></h4>
            <iframe class="snapwidget-widget hidden-md-up" src="https://snapwidget.com/embed/485561" allowTransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:350px; height:125px"></iframe>
        </div>

    </div>
  </footer>

</body>
</html>

website/templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load customtags %}


{% block meta-title %}¿Quienes formamos ChooseTravel?{% endblock %}
{% block meta-description %}Encuentra los rincones más bonitos de España a través de nuestras experiencias y descubre otros muchos viajes por el mundo.{% endblock %}
{% block meta-image %}http://www.choosetravel.es/static/img/travel/2016_10_22_Nueva%20York/banner.jpg{% endblock %}
{% block meta-url %}http://choosetravel.es/{% endblock %}

{% block content %}

<p class="display-4">¿Quienes somos?</p>
<hr>
<div class="mb-5">
  <p class="m-5 font-italic text-center h4">
    “Un viaje se mide mejor en amigos que en millas” – <span class="text-muted">Tim Cahill</span>
  </p>
  <p>
    En nuestras experiencias hemos aprendido que viajar, como convivir, es algo muy íntimo y no cualquier persona vale para ello.
    Cada uno viajamos por distintas razones y con distintos objetivos, por lo que saber convivir y ser amable no es suficiente a
    a la hora de elegir un compañero de viaje, es necesario tener unos puntos en común para poder satisfacer los deseos de todos.
  </p>
  <p>
    Los que aquí aparecemos somos ya amigos y compañeros de viaje con bastante antigüedad, por ello que la mayoria de viajes los
    hayamos realizado juntos, como podréis ver en muchas de las fotos. Sin más, os dejo las fichas.
  </p>
</div>


<div class="row">

  <div class="col-md-4 mb-4">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" style="height:200px;background-image: url('{% static 'img/david.amrani.jpg' %}');background-size: cover;">
      <div class="card-block">
        <h4 class="card-title">David Amrani H.</h4>
        <p class="card-text font-italic">“Viajar es un ejercicio con fatales consecuencias para los prejuicios, la intolerancia y la mente estrecha"</p>
      </div>
      <div class="card-footer pb-2 pt-2">
        <p class="text-muted m-0 d-flex justify-content-between">
          <small class="pt-1">Developer & Collaborator</small>
          <span>
            <a href="https://www.instagram.com/davidmoremad/" target="_blank" class="text-muted"><i class="fa fa-instagram fa-lg mr-2"></i></a>
            <a href="https://www.linkedin.com/in/davidah/" target="_blank" class="text-muted"><i class="fa fa-linkedin fa-lg mr-2"></i></a>
            <a href="https://github.com/davidmoremad" target="_blank" class="text-muted"><i class="fa fa-github fa-lg mr-2"></i></a>
            <a href="https://twitter.com/davidmoremad" target="_blank" class="text-muted"><i class="fa fa-twitter fa-lg"></i></a>
          </span>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-4 mb-4">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" style="height:200px;background-image: url('{% static 'img/javier.torre.jpg' %}');background-size: cover;">
      <div class="card-block">
        <h4 class="card-title">Javier de la Torre C.</h4>
        <p class="card-text font-italic">“Viajar sirve para ajustar la imaginación a la realidad, y para ver las cosas como son en vez de pensar cómo serán”</p>
      </div>
      <div class="card-footer pb-2 pt-2">
        <p class="text-muted m-0 d-flex justify-content-between">
          <small class="pt-1">Collaborator</small>
          <span>
            <a href="https://instagram.com/javitc7" target="_blank" class="text-muted"><i class="fa fa-instagram fa-lg mr-2"></i></a>
            <a href="https://www.linkedin.com/in/javierdelatorrecriado/" target="_blank" class="text-muted"><i class="fa fa-linkedin fa-lg mr-2"></i></a>
          </span>
        </p>
      </div>
    </div>
  </div>


  <div class="col-md-4 mb-4">
    <div class="card" style="width: 20rem;">
      <img class="card-img-top" style="height:200px;background-image: url('{% static 'img/nacho.lazaro.jpg' %}');background-size: cover;">
      <div class="card-block">
        <h4 class="card-title">Nacho Lázaro C.</h4>
        <p class="card-text font-italic">“El deambular re-establece la armonía original que alguna vez existió entre el hombre y el Universo”</p>
      </div>
      <div class="card-footer pb-2 pt-2">
        <p class="text-muted m-0 d-flex justify-content-between">
          <small class="pt-1">Collaborator</small>
          <span>
            <a href="https://www.instagram.com/nachz10lc/" target="_blank" class="text-muted"><i class="fa fa-instagram fa-lg mr-2"></i></a>
            <a href="https://www.linkedin.com/in/ignacio-l%C3%A1zaro-carrasco-763a6613b/" target="_blank" class="text-muted"><i class="fa fa-linkedin fa-lg mr-2"></i></a>
          </span>
        </p>
      </div>
    </div>
  </div>

</div>
  {% endblock%}

website/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load customtags %}


{% block meta-title %}Descubre los rincones más bellos de España y Europa{% endblock %}
{% block meta-description %}Encuentra los rincones más bonitos de España a través de nuestras experiencias y descubre otros muchos viajes por el mundo.{% endblock %}
{% block meta-image %}http://www.choosetravel.es/static/img/travel/2016_10_22_Nueva%20York/banner.jpg{% endblock %}
{% block meta-url %}http://choosetravel.es/{% endblock %}

{% block content %}
<p class="display-4">Encuentra algo cerca para visitar</p>
<div style="height:340px; width:100%; display:inline-block; overflow:hidden; margin-bottom:-50px;">
 <iframe style="position:relative;top:-51px; border:none;" src="https://www.google.es/maps/d/embed?mid=1N8qJ6NL33lG22qXl1zQmcEr_0o0K7Qeu" width="100%" height="340px"></iframe>
</div>

<hr>

<h3 class="text-right text-muted mb-3">...o planifica <u>tu próximo viaje</u>:</h3>
<div class="card-deck row">
  {% for travel in travels %}
  <div class="col-md-4 mb-3">
    <div class="card w-100"  style="width: 300px;">
      <img class="card-img-top" style="height:200px;background-image: url('{%for photo in travel.gallery.all%}{% if photo.banner %}{% static photo.image.url %}{% endif %}{%endfor%}');background-size: cover;">
      <div class="card-block"  style="height:180px;">
        <h4 class="card-title"><a href="{% url 'website:travel_detail' pk=travel.pk %}">{{travel.title}}</a></h4>
        <p class="card-text">{{travel.description}}</p>
      </div>
      <div class="card-footer">
        <div class="d-flex justify-content-between">
          <span class="badge badge-pill badge-default badge-{{travel.score|score_color}}"> <i class="fa fa-star"></i> &nbsp;{{travel.score}}/10</span>
          <span class="badge badge-pill text-muted"> <i class="fa fa-snowflake-o"></i> &nbsp;{{travel.season|title}}</span>
          <span class="badge badge-pill badge-default badge-{{travel.price|price_color}}"> <i class="fa fa-usd"></i> &nbsp;{{travel.price}}</span>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock%}

website/templates/travel/detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load customtags %}

{% block meta-title %}Mi viaje a {{travel.title}} {% endblock %}
{% block meta-description %} {{travel.description}} {% endblock %}
{% block meta-image %}http://www.choosetravel.es/static/img/travel/{{travel.date|date:"Y_m_d"}}_{{travel.title}}/banner.jpg{% endblock %}
{% block meta-url %}http://choosetravel.es/travel/{{travel.id}}{% endblock %}


{% block content %}
<link href="{% static 'css/lightbox.css' %}" rel="stylesheet">
<style media="screen">
  .carousel-inner .carousel-item-right.active,
  .carousel-inner .carousel-item-next {
  transform: translateX(25%);
  }
  .carousel-inner .carousel-item-left.active,
  .carousel-inner .carousel-item-prev {
  transform: translateX(-25%)
  }
  .carousel-inner .carousel-item-right,
  .carousel-inner .carousel-item-left{
  transform: translateX(0);
  }
</style>

<div class="row">
  <div class="col-md-12 mb-4">

    <h1 class="display-4">{{travel.title}}{% include 'utils/admin-toolbar.html' %}</h1><hr>

    <!-- MOBILE BASIC INFO -->
    <ul class="hidden-md-up nav nav-pills nav-fill bg-faded">
        <li class="nav-item bg-{{travel.price|price_color}}"><span class="nav-link border border-primary"><i class="fa fa-usd"></i> {{travel.price}} €</span></li>
        <li class="nav-item bg-{{travel.score|score_color}}"><span class="nav-link"><i class="fa fa-star"></i> {{travel.score}} /10</span></li>
        <li class="nav-item"><span class="nav-link"><i class="fa fa-snowflake-o"></i> {{travel.season|title}}</span></li>
    </ul>

    <!-- CAROUSEL OF PICTURES -->
    <div id="recipeCarousel" class="carousel slide w-100 " data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        {% for photo in travel.gallery.all %}
          <a href="{%static photo.image.url%}" data-lightbox="roadtrip" data-title="{{travel.title}}" class="carousel-item {%if forloop.counter0 == 0 %}active{%endif%}">
              <span class="col-md-3 m-1" style="height:200px;background-image: url('{%static photo.image.url%}');background-size: cover;border:none"></span></a>
        {%endfor%}
      </div>
      <a class="carousel-control-prev" href="#recipeCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#recipeCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <!-- GOOGLE MAP -->
  <div class="col-md-9">
    <div style="height:340px; width:100%; display:inline-block; overflow:hidden; margin-bottom:-50px">
     <iframe style="position:relative;top:-51px; border:none;" src="{{travel.geo|safe}}" width="100%" height="340px"></iframe>
    </div>
    <small class="float-right text-muted font-italic" style="position:relative">Ver en <a target="_blank" href="{{travel.geo|safe}}">Google Maps</a></small>
    <p>{{travel.text|safe}}</p>
  </div>

  <!-- DESKTOP BASIC INFO -->
  <div class="col-md-3 hidden-md-down">
    <ul class="list-group">
      <li class="list-group-item h5 text-{{travel.price|price_color}}">
        <div class="col-md-2 text-center"><i class="fa fa-usd"></i></div>
        <div class="col-md-10 text-right"> {{travel.price}} €</div>
      </li>
      <li class="list-group-item h5 text-{{travel.score|score_color}}">
        <div class="col-md-2 text-center"><i class="fa fa-star"></i></div>
        <div class="col-md-10 text-right"> {{travel.score}} / 10</div>
      </li>
      <li class="list-group-item h5">
        <div class="col-md-2 text-center"><i class="fa fa-map-marker"></i></div>
        <div class="col-md-10 text-right"> {{travel.country.name}}</div>
      </li>
      <li class="list-group-item h5">
        <div class="col-md-2 text-center"><i class="fa fa-snowflake-o"></i></div>
        <div class="col-md-10 text-right"> {{travel.season|title}}</div>
      </li>
    </ul>
  </div>

</div>



<script src="{% static 'js/lightbox.js'%}"></script>
<script type="text/javascript">
$('#recipeCarousel').carousel({
  interval: 2222
})
$('.carousel .carousel-item').each(function(){
    var next = $(this).next();
    // Return first if it is the last
    if (!next.length) {
      next = $(this).siblings(':first');
    }
    next.children(':first-child').clone().appendTo($(this));
    if (next.next().length>0) {
      next.next().children(':first-child').clone().appendTo($(this));
    }
    else {
      $(this).siblings(':first').children(':first-child').clone().appendTo($(this));
    }
    if (next.next().next().length>0) {
      next.next().next().children(':first-child').clone().appendTo($(this));
    }
    else {
      $(this).siblings(':first').children(':first-child').clone().appendTo($(this));
    }
});
</script>

{% endblock%}

website/templates/travel/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load customtags %}

{% block meta-title %}Descubre los rincones más bellos de España y Europa{% endblock %}
{% block meta-description %}Historia de mis viajes por {%for travel in travels%}{{travel.title}}, {%endfor%}{% endblock %}
{% block meta-image %}http://www.choosetravel.es/static/img/travel/2016_10_22_Nueva%20York/banner.jpg{% endblock %}
{% block meta-url %}http://choosetravel.es/travels/{% endblock %}

{% block content %}

<p class="display-4">Mis viajes</p> <hr>
<ul class="list-group mt-2">
  {% for travel in travels %}
  <li class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between ">
        <span class="h5 align-middle mb-1"><a href="/travel/{{travel.id}}">{{travel.title}}</a>, {{travel.country.name}} </span>
        <span class="col-3 text-right">
          <span style="width:60px" class="p-1 ml-2 badge badge-default badge-{{travel.price|price_color}}"><i class="fa fa-usd fa-lg"></i> {{travel.price}}</span>
          <span style="width:60px" class="p-1 ml-2 badge badge-default badge-{{travel.score|score_color}}"><i class="fa fa-star fa-lg"></i> {{travel.score}}/10</span>
        </span>
      </div>
  </li>
  {% endfor %}
</ul>

{% endblock%}

website/templates/utils/admin-toolbar.html
{%if user.is_superuser%}
  <div class="float-right h-100">

  {%if travel%}
  <div class="d-inline align-middle"><a class="btn btn-info" role="button" href="/admin/website/travel/{{travel.id}}/change/"><i class="fa fa-pencil"></i></a></div>
  {%endif%}
  <div class="d-inline align-middle"><a class="btn btn-info" role="button" href="/admin/website/travel/add/"><i class="fa fa-plus"></i></a></div>
</div>
{%endif%}